# Generated by Django 5.1.2 on 2025-01-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('RN', 'RUNNING'), ('SN', 'SNEAKER'), ('MX', 'MAX'), ('DN', 'DUNKS'), ('JR', 'JORDAN'), ('AR', 'AIR DN'), ('FR', 'AIR FORCE'), ('VA', 'VAPORFLY'), ('VK', 'V2K')], max_length=50)),
                ('product_image', models.ImageField(upload_to='products')),
            ],
        ),
    ]
